POST http://localhost:8081/user
content-type: application/json

{
"nome": "adendo",
"sobrenome": "adentro",
"idade": 14
}

###
POST http://localhost:8081/cadastrar

###
POST http://localhost:8081/login



####
POST https://polar-beyond-82520.herokuapp.com/temps
content-type: application/json

{
//"_id": "2",
"local": "sala",
"temperatura": "14",
"dia":"18",
"mes":"06",
"ano":"2022"
}
###

GET http://localhost:8081/temps

###
GET https://polar-beyond-82520.herokuapp.com/temps

###
GET http://localhost:8081/temps/mqtt



###
PATCH   http://localhost:8081/user/1
content-type: application/json

{
"nome": "lulu",
"sobrenome": "kawahara",
"idade": 15
}

###
PATCH   https://polar-beyond-82520.herokuapp.com/temps
content-type: application/json

{
"local": "sala",
"temperatura": "18",
"dia": "22",
"mes": "06",
"ano": "2022"
}


###
DELETE  https://polar-beyond-82520.herokuapp.com/temps/62ba1af4dd10d6f7d1d5bce0





